dont fail on no update'

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -25,11 +25,28 @@ commands:
                   --region=us-east-1 
               else
                 echo "Updating stack..."
-                aws cloudformation update-stack \
+                # source: https://gist.github.com/mdjnewman/b9d722188f4f9c6bb277a37619665e77
+                set +e
+                update_output=$(aws cloudformation update-stack \
                   --stack-name <<parameters.stack-name>> \
                   --template-body <<parameters.template-body>> \
                   --parameters <<parameters.parameters>> \
-                  --region=us-east-1 
+                  --region=us-east-1)
+                status=$?
+                set -e
+
+                echo "$update_output"
+
+                if [ $status -ne 0 ] ; then
+
+                  # Don't fail for no-op update
+                  if [[ $update_output == *"ValidationError"* && $update_output == *"No updates"* ]] ; then
+                    echo -e "\nFinished create/update - no updates to be performed"
+                    exit 0
+                  else
+                    exit $status
+                  fi
+                fi
             fi
 
 jobs:
